# Generated by Django 3.2.7 on 2023-11-03 13:47

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231103_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),  # Otomatik olarak oluşturulma zamanını kaydeder
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='id',
            field=models.AutoField(primary_key=True),  # Otomatik artan birincil anahtar
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),  # Otomatik olarak güncelleme zamanını kaydeder
        ),
        migrations.AddField(
            model_name='imagesetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),  # Otomatik olarak oluşturulma zamanını kaydeder
        ),
        migrations.AddField(
            model_name='imagesetting',
            name='id',
            field=models.AutoField(primary_key=True),  # Otomatik artan birincil anahtar
        ),
        migrations.AddField(
            model_name='imagesetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),  # Otomatik olarak güncelleme zamanını kaydeder
        ),
    ]
