# Generated by Django 3.2.7 on 2023-11-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('school_name', models.CharField(blank=True, max_length=254, verbose_name='School Name')),
                ('major', models.CharField(blank=True, max_length=254, verbose_name='Major')),
                ('department', models.CharField(blank=True, max_length=254, verbose_name='Department')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
